### ISSUE TITLE
hosted form example: using hostedPaymentSettings vs hostedProfileSettings?

### ISSUE THREAD

**Issue by witekdev** [AuthorizeNet/sample-code-python#27]
On https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/get-hosted-payment-page.py#L33

Shouldn't that line use the hostedPaymentSettings property instead of hostedProfileSettings as per:
https://developer.authorize.net/api/reference/features/accept_hosted.html and https://github.com/AuthorizeNet/sample-code-ruby/blob/master/PaymentTransactions/get-hosted-payment-page.rb#L30

**Comment by witekdev** [comment]
Well I guess one way to not have errors in your examples, is to just remove the offending example completely.

**Comment by adavidw** [comment]
Not removed - just renamed [in a previous commit](https://github.com/AuthorizeNet/sample-code-python/commit/dcbd160990bfa2d5c1a523135c620465b5628679)

**Comment by adavidw** [comment]
And, [now it's fixed](https://github.com/AuthorizeNet/sample-code-python/commit/8aa264a7b4d820c59e0e6936454da9778da96aef).

Sorry this slipped through the cracks, but at least you called attention to it so I could make the fix. Thanks for reporting the issue.

**Comment by witekdev** [comment]
@adavidw ok, thanks for picking this up. and while I have your attention:

http://www.authorize.net/content/dam/authorize/documents/SIM_guide.pdf#page=10
The SIM docs (which I'm now implementing instead of Accepted Hosted at a clients explicit instructions) dated Feb 2017, on page 10 provide a link to:
https://developer.authorize.net/integration/fifteenminutes#hosted.
which then routes one to:
http://developer.authorize.net/hello_world/#hosted.
Which doesn't help a SIM developer as it's accepted hosted related code. Anyway, I know SIM is on its way out, so perhaps this is not a priority for you guys to fix, but if you are going to put out what appears to be updated docs (Feb 2017) for solution you still support (SIM), would be good if the docs maintained their integrity? 
But so far so good, I have been able to google and forum my way out of SIM issues I encountered so far. 

Also here are some issues I reported earlier this year on the Accepted Hosted API docs that seem to have slipped through the cracks:
https://github.com/AuthorizeNet/sdk-python/issues/69

Thanks!

**Comment by adavidw** [comment]
> and while I have your attention

Uh oh. Should have stayed incognito. Just kidding - I'm always happy to help. Yes, SIM is obviously on the way out, but it is supported, and documentation should be correct. I've opened a ticket with the documentation team to either incorporate the sample into the PDF, change the link to a new location for the sample, or (worst case) replacing that section with something that says "No sample code is available for this. Sorry". Hopefully it doesn't come to that last one.

> Also here are some issues I reported earlier this year...

Again, sorry. I will say that Authorize.Net has really found religion about making sure that developers have a world class experience working with their services. However, I'm the first new hire for developer outreach since that shift in focus, so I'm sometimes trying to fix every pain point myself. I'm just one guy with only two hands (and those hands each have only five fingers). Enough excuses, though. I'll go address that one right now.

**Comment by witekdev** [comment]
@adavidw regaining developer trust one developer at a time :) I've seen you active on the forums. Thanks for the effort.
